### ISSUE TITLE
Initial Editor Checklist

### ISSUE THREAD

**Issue by codementum** [journalovi/2023-park-gatherplots#1]
- [x] Check that the HTML version is in the repo as index.html and renders to the JoVI format (refer to https://github.com/journalovi/jovi-template-quarto)
- [x] Uses something similar to the template
- [x] Includes author information
- [x] Includes abstract box
- [x] Includes infobox required paper sections
   - [x] Research materials
   - [x] Authorship
   - [x] License
   - [x] Conflicts of Interest
   - [x] Includes table of contents
- [x] Add a notice infobox that the paper is under review w/ link to github issues above the abstract:
   ```
   ::: {.callout-important appearance="simple"}
   ## Under Review {.unnumbered}
   This paper is under review on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/).
   :::
   ```
- [x] Set up github pages
   - [x] Settings -> Actions -> General -> Allow journalovi, and select non-journalovi, actions. Enter: 
      `actions/*,quarto-dev/*`
      ![image](https://github.com/journalovi/2023-park-gatherplots/assets/6345019/05018b2f-f00e-4019-92de-cced0aab0d72)
   - [x] clone the repo locally
   - [x] run this command in the repo directory:
      ```
      quarto publish gh-pages index.qmd
      ```
- [x] From the main repo page, click the settings gear icon next to "About" on the right. 
   - [x] Under "Description" enter "UNDER REVIEW"
   - [x] Under "Website" tick "Use Your Github Pages Website".
- [x] Edit README.md and add the following at the very top:
   ````
   ```diff
   ! This paper is under review on the experimental track of the Journal of Visualization and Interaction.
   ```
   ````
- [x] double-check the paper is rendering correctly on github pages.
- [x] ~~ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the [transparency section of the author guide](https://www.journalovi.org/author-guide.html#transparency-requirements)~~ See #5

**Comment by nickelm** [comment]
> ensure all appropriate supplemental materials are included: e.g. experimental data, experimental analysis code, source code for artifacts, etc. For a full list of requirements see the transparency section of the author guide

This is well received. In response, I have collected further material from my coauthors and uploaded the available files and protocols to OSF (https://osf.io/bk9cx/). However, as noted by several reviewers, this is an older project that was completed some time ago; in fact, the study was run in 2014. Both students who participated in the project have moved on to faculty careers of their own. The students have all provided all available files, but it is not complete. I have uploaded what I was able to recover. I hope that this article's value supersedes its weaknesses in research transparency.

The analysis for the study data was recently updated in preparation for this submission and is available. I have uploaded it to the OSF as `bootstrap.html`. Note, however, that this is an interactive JavaScript application designed to be run with an active user. The Vega JSON files it generates for producing the SVG plots were already to be found in the `plots/` folder.

> check they are in appropriate long-term repositories (e.g. OSF, Zenodo, etc). Github repositories are okay as long as they are also archived on something like OSF or Zenodo. One easy way to archive + DOI an existing github repo is with Zenodo; see here

I have added the GitHub repository to the OSF (https://osf.io/bk9cx/). I will create a registration at the end of the major revision process (and after additional future revisions).

> check they are listed in the abstract and the required Materials section of the paper

The OSF is indeed listed in the abstract (under Materials).

> if any materials are missing, create an issue tagging the authors and ask them to add those materials

Please let me know if anything is still missing.

**Comment by mjskay** [comment]
This checklist is now complete, closing it.
