### ISSUE TITLE
[PRE-REVIEW] Infrastructure Setup Checklist

### ISSUE THREAD

**Issue by mjskay** [journalovi/2023-park-gatherplots#21]
- [x] Set up Github pages
   - [x] If the paper requires compilation:
      - [x] Ensure it has a workflow file, such as `.github/workflows/publish.yml`, that compiles the paper and copies the compiled result to the root folder of the `gh-pages` branch. Some example workflow files:
         - [Quarto](https://github.com/journalovi/jovi-template-quarto/blob/main/.github/workflows/publish.yml)
         - [Idyll](https://github.com/journalovi/2024-Cashman-PAC-learning-game/blob/master/.github/workflows/publish.yml) - this template can be easily adapted for other workflows that use custom tools for building, e.g. npm or yarn, by swapping out the `npm` commands and ensuring the correct output folder is copied to the `gh-pages` branch in the last step.
      - [x] Go to **Settings -> Pages**:
         - [x] Set "Source" to "Deploy from a branch"
         - [x] Set "Branch" to "gh-pages"
         - [x] Set the folder to "/"
      - [x] Verify the compilation works. On the repo page, go to Actions and click on the "XXX Publish" (XXX = Quarto/Idyll/etc) workflow on the left, then click Run Workflow and run it.
   - [x] Verify that the "pages build and deployment" action is successful.
   - [x] Check that the live version of the article is visible at http://www.journalovi.org/20XX-YY-ZZ (replace the last part with the repo name).
- [x] Ensure the paper contains a notice infobox at the top that the paper is under review and that the repository links in the notice are correct (by replacing the `20xx-repo-name` part with the repository name).

   In Quarto this looks like:

   ```
   ::: {.callout-important appearance="simple"}
   ## Under Review {.unnumbered}
   This paper is [under review](https://www.journalovi.org/under-review.html) on the experimental track of the [Journal of Visualization and Interaction](https://www.journalovi.org/). See the [reviewing process](https://github.com/journalovi/20xx-repo-name/issues).
   :::
   ```

   In HTML this could be:

   ```
   <p><strong>Under Review:</strong> This paper is <a href="https://www.journalovi.org/under-review.html">under review</a> on the experimental track of the <a href="https://www.journalovi.org/">Journal of Visualization and Interaction</a>. See the <a href="https://github.com/journalovi/20xx-repo-name/issues">reviewing process</a>.</p>
   ```
   - [x] In the info box, ensure “20xx-repo-name” is replaced with the name of the repository so that the link points to the Issues page on Github.
   - [x] Check that the live version of the paper now has the infobox in it with the correct links. You may need to go to the Actions page to check that the build process has completed, then go back to the live paper URL. You might need to reload the article without cache (In Chrome: Cmd + Shift + R (Mac) or Ctrl+ Shift + R (Windows)).
- [x] Compare the paper with the authors’ compiled version that the authors submitted. Sample the figures and interactive elements to see if they are present and work in the same way.
- [x] ~~Check that the article works locally without an internet connection:~~ moved to #22 
   - [x] Check out the repo and switch to whatever branch serves the site (e.g. `main` or `master` for sites without compilation, `gh-pages` for sites with compilation).
   - [x] With the internet off (e.g. in airplane mode), ensure the page loads in a browser. Sample the figures and interactive elements to see if they are present and work in the same way. You may need to use a local server from the repo directory:
         
      ```sh
      python -m http.server
      ```
- [x] From the [main repo page](../), click the settings gear icon next to "About" on the right. (If you cannot see the “About” section, make your web browser window wider.)
   - [x] Under "Description" enter "UNDER REVIEW"
   - [x] Under "Website" tick "Use Your Github Pages Website".
   - [x] Click “Save changes”
- [x] Edit README.md and add the following at the very top:
   ````
   ```diff
   ! This paper is under review on the experimental track of the Journal of Visualization and Interaction.
   Authors: [insert Github IDs]
   OC: TBD
   AE: TBD
   R1: TBD
   R2: TBD
   R3: TBD
   ```
   ````
- [x] Replace `[insert Github IDs]` in `README.md` with the authors' Github IDs.
- [x] When an OC has been assigned to this paper, replace the `TBD` under `OC:` in `README.md` with the Github ID of the OC.
- [x] Enable branch protection on the repository:
   - [x] Under Settings -> Branches, click "Add branch protection rule"
   - [x] Under "Branch name pattern", enter "main" or "master" (whichever applies to this repo)
   - [x] Click "Create"
   - [x] Check that the newly-created rule says "Currently applies to 1 branch" next to it.
- [x] Ensure that the authors have write access to the repo:
   - [x] Under Settings -> Collaborators and Teams, click "Add people"
   - [x] Enter the Github usernames for each author as provided by the authors. Give each one "Write" access.
- [x] Re-render [under-review.qmd](https://github.com/journalovi/journalovi.github.io/blob/main/under-review.qmd) on the JoVI website (See instructions in the source code). Ensure that the added paper is listed on the [Under Review](https://www.journalovi.org/under-review.html) page in the correct location.
- [x] When this checklist is complete, create the following issues and tag the relevant people (Github IDs are listed on [People page](https://www.journalovi.org/people.html)), then close this issue:
   - [x] [Recruit Associate Editor](new?assignees=&labels=pre-review&projects=&template=91_tech_org-recruit_editor.md&title=%5BPRE-REVIEW%5D+Recruit+Associate+Editor) (assign to the OC of this paper) (**NOTE:** this part of the process may change as we evolve the Editor-Wrangler role)
   - [x] [Open Materials Review](new?assignees=&labels=review&projects=&template=92_tech_open-review.md&title=%5BREVIEW%5D+Open+Materials+Review) (assign to the Open Practices Chair)
   - [x] [Accessibility Review Request](new?assignees=&labels=pre-review&projects=&template=93_tech_acc-review_request.md&title=%5BPRE-REVIEW%5D+Accessibility+Review+Request) (assign to the Accessibility Chair)

**Comment by mjskay** [comment]
This checklist is now complete, with the exception of #22, which we will deal with when upstream fixes allow us to make Observable.js content fully standalone.
